server:
  port: 8081

spring:
  profiles:
    active: test

person:
  name: littlexx
  age: 18
  boss: true
  birth: 1997/08/02
  maps: {k1: v1, k2: v2}
  lists:
    - wenglingzi
    - chenggang
    - renyumei
    - huangyouping
    - sunwenyou
  dog:
    name: xixixi
    age: 5

---
server:
  port: 8082
spring:
  profiles: dev

---
server:
  port: 8083

spring:
  profiles: prod

---
server:
  port: 8084

spring:
  profiles: test